### ISSUE TITLE
how to save the stack board as template

### ISSUE THREAD

**Issue by venki1410** [fluttercandies/stack_board#2]
我正在尝试创建一个画布，用户可以在其中将他们的编辑保存为草稿。有没有办法将堆栈板保存为模板。

**Comment by xSILENCEx** [comment]
近期会进行一次重构，新版本会加入该功能
A refactoring will be done in the near future, and the new version will add this feature

**Comment by KetanSatani-TheOneTech** [comment]
@xSILENCEx 

Hello, Have you got any time on this feature?

https://github.com/fluttercandies/stack_board/issues/2#issuecomment-1151770442
