### ISSUE TITLE
Example Provided Error

### ISSUE THREAD

**Issue by RoyalCoder88** [fluttercandies/stack_board#5]
Hi, thanks for your great package, I got the provided example from GitHub but I get this error:

```
Exception has occurred.
FlutterError (There are multiple heroes that share the same tag within a subtree.
Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
# Here is the subtree for one of the offending heroes: Hero)
```

*also can you guide me on how can I achieve **saving** for the StackBoard data for example like a .json?
Thanks in advance!

**Comment by xSILENCEx** [comment]
1. You may be using Hero animations incorrectly
2. add `toJson` on [0.2.0](https://pub.dev/packages/stack_board)
